version: '3.8'

services:
  web:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .flaskenv.env
    depends_on:
      - db
  db:
    image: postgres:16
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=11111
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    expose:
      - 5432